version: "3"

services:
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml # Mount the envoy.yaml file into the container
    ports:
      - "10000:10000"
      - "9901:9901" # Envoy admin interface port

